#!/bin/bash
#PBS -N fingerprint
#PBS -l nodes=1:ppn=4:turtle
#PBS -q batch
#PBS -j oe
#PBS -o fingerprint.log
##PBS -m abe
##PBS -M tommy_lin@berkeley.edu

start_time=$(date +%s)

source ~/.bashrc
export PATH="/home/tommylin/miniconda3/bin:$PATH"
source ~/miniconda3/etc/profile.d/conda.sh
conda activate myenv

echo $HOSTNAME

cd $PBS_O_WORKDIR
nohup python extract_fingerprint.py 2>&1 &
wait

end_time=$(date +%s)
runtime=$((end_time - start_time))
echo "Total runtime: $runtime seconds"